"""
LLM Call Module – Milestone 4
"""

def call_llm(prompt: str):
    """
    Placeholder LLM call.
    Replace with OpenAI / HuggingFace / Ollama later.
    """
    return (
        "This is a placeholder answer generated by the LLM module.\n\n"
        "Prompt received:\n"
        f"{prompt[:500]}"
    )
